/*
 * System Log (Okta API)
 *
 * The Okta System Log API (https://developer.okta.com/docs/api/resources/system_log) provides read access to your organization's system log. The API is intended to export event data as a batch job from your organization to another system for reporting or analysis.
 *
 * API version: 1.0
 * Contact: rnd@forter.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package oktapi

// Log Events from Syslog
type LogEvent struct {
	Actor                 Actor                  `json:"actor"`
	Uuid                  string                 `json:"uuid"`
	Published             string                 `json:"published"`
	EventType             string                 `json:"eventType"`
	Version               string                 `json:"version"`
	Severity              string                 `json:"severity"`
	LegacyEventType       string                 `json:"legacyEventType,omitempty"`
	DisplayMessage        string                 `json:"displayMessage,omitempty"`
	Client                Client                 `json:"client,omitempty"`
	Outcome               LogEventOutcome        `json:"outcome,omitempty"`
	Target                []Target               `json:"target,omitempty"`
	Transaction           Transaction            `json:"transaction,omitempty"`
	DebugContext          map[string]interface{} `json:"debugContext,omitempty"`
	AuthenticationContext AuthenticationContext  `json:"authenticationContext,omitempty"`
	SecurityContext       SecurityContext        `json:"securityContext,omitempty"`
	Request               map[string]interface{} `json:"request,omitempty"`
}
